### ISSUE TITLE
Meta tag problem on template

### ISSUE THREAD

**Issue by buraste** [papan01/gatsby-starter-papan01#1]
Hello there, I used this repo for my personal blog and it is such a amazing, but I couldn't right meta tags. Other websites can't reach my manifest.webmanifest file so can't read my site title, description and logo. Also my app can't render Helmet component in index.jsx file,
I checked [papan01's](https://papan01.com) and [gatsby-starter-papan01's](https://gatsby-starter-papan01.netlify.com/) meta tags and same situation. Also you can check them on [heymeta.com](https://www.heymeta.com/url/papan01.com/), or [metatags.io](https://metatags.io/) or any similar site.
How can we solve this problem?

**Comment by papan01** [comment]
I appreciate your kind assistance🙇🏼. In my website, I can find my meta tags:
```html
<title>Papan01's Blog</title>
<link rel="canonical" href="https://papan01.com" data-react-helmet="true">
<meta name="theme-color" content="#282c35" data-react-helmet="true">
<meta name="description" content="Personal blog by Papan01. Life and code." data-react-helmet="true">
<meta name="image" content="https://papan01.com/favicons/logo.png" data-react-helmet="true">
<meta property="og:site_name" content="Papan01's Blog" data-react-helmet="true">
<meta property="og:url" content="https://papan01.com" data-react-helmet="true">
<meta property="og:title" content="Papan01's Blog" data-react-helmet="true">
<meta property="og:description" content="Personal blog by Papan01. Life and code." data-react-helmet="true">
<meta property="og:image" content="https://papan01.com/favicons/logo.png" data-react-helmet="true">
<meta property="og:image:alt" content="Personal blog by Papan01. Life and code." data-react-helmet="true">
<meta name="twitter:card" content="summary_large_image" data-react-helmet="true">
<meta name="twitter:creator" content="" data-react-helmet="true">
<meta name="twitter:title" content="Papan01's Blog" data-react-helmet="true">
<meta name="twitter:description" content="Personal blog by Papan01. Life and code." data-react-helmet="true">
<meta name="twitter:image" content="https://papan01.com/favicons/logo.png" data-react-helmet="true">
<meta name="twitter:image:alt" content="Personal blog by Papan01. Life and code." data-react-helmet="true">
```
But on [heymeta.com](https://www.heymeta.com/url/papan01.com/), or [metatags.io](https://metatags.io/) can't detect them, please give me some time, I will try to solve them.

**Comment by buraste** [comment]
Still same, sorry. 
I can't find my meta tags in page source. So when I share any blog post or my webiste url (like Linkedin, Instagram, Twitter), preview is poor. 

Btw, I plan to prepare a tutorial about making website with Gatsby.js and I want to use your repo (If it isn't problem for u). Maybe more people can see your amazing works. Before this, I discover all of things about Gatsby and ur repo.

**Comment by papan01** [comment]
Do you add SEO component in your page? If so, you would find your meta tags in DevTools.
I found same issue that it can't show preview: https://github.com/gatsbyjs/gatsby/issues/9979,
unfortunately, there is no explicit solution. I am trying to solve this problem.

Thank you for appreciating this repository, you could use anywhere👍🏻.

**Comment by papan01** [comment]
@mindlabcore 
I found the issue. I did't install `gatsby-plugin-react-helmet`. It support server-side-render.
<img width="992" alt="螢幕快照 2020-02-24 下午9 02 29" src="https://user-images.githubusercontent.com/17759583/75154602-08cb6d00-5749-11ea-8cda-a2f5517636b6.png">
<img width="980" alt="螢幕快照 2020-02-24 下午9 02 42" src="https://user-images.githubusercontent.com/17759583/75154608-0b2dc700-5749-11ea-8257-0d5266c556e9.png">

Could you help me to check this issue is solved?
I will merge to master, if it has no problem.

**Comment by buraste** [comment]
Dear, I was about to turn on same PR. Then I saw your comment. It was absolutely done! Thanks for your effort.
