### ISSUE TITLE
Word wrapping problem

### ISSUE THREAD

**Issue by buraste** [papan01/gatsby-starter-papan01#3]
Hello my friend! I can't open PR. If the sentence is too long to fit on the line, the separation of the letters seems erroneous. I solved the problem by deleting word-break line at layout/style/style.scss@34:
```
div,
form,
p {
  margin: 0;
  padding: 0;
  word-break: break-all;
}
```
On homepage:
![image](https://user-images.githubusercontent.com/44535256/76712496-b1f2fb00-672a-11ea-82c5-ee5075e3d820.png)

On post:
![image](https://user-images.githubusercontent.com/44535256/76712514-cdf69c80-672a-11ea-8dc8-c7a2c3cb0079.png)

**Comment by papan01** [comment]
Thanks, bro!I'll create a PR for this👍🏻.
